package com.ppsu.placement.examples;

import java.util.List;
import java.util.Optional;
import org.springframework.stereotype.Component;

/**
 * The session script as data: one entry per example, in the order the session shows them.
 * The pages /examples and /examples/{id} are generated from this list, so the guide and the code cannot drift apart
 * unnoticed (ExamplesTest runs every Run button below and checks the status code).
 */
@Component
public class ExampleCatalog {
    private static final String JSON = "application/json";
    private static final String FORM = "application/x-www-form-urlencoded";

    private final List<Example> all = List.of(
            h1(), h2(), h3(), h4(), h5(), h6(), h7(), h8(),
            m1(), m2(), m3(), m4(), m5(), m6(), m7(), m8());

    public List<Example> all() {
        return all;
    }

    public Optional<Example> find(String id) {
        return all.stream().filter(e -> e.id.equalsIgnoreCase(id)).findFirst();
    }

    public Optional<Example> previous(String id) {
        int i = indexOf(id);
        return i > 0 ? Optional.of(all.get(i - 1)) : Optional.empty();
    }

    public Optional<Example> next(String id) {
        int i = indexOf(id);
        return i >= 0 && i < all.size() - 1 ? Optional.of(all.get(i + 1)) : Optional.empty();
    }

    private int indexOf(String id) {
        for (int i = 0; i < all.size(); i++) if (all.get(i).id.equalsIgnoreCase(id)) return i;
        return -1;
    }

    // ===================================== Part A. Hibernate =====================================

    private static Example h1() {
        return new Example("h1", "Hibernate", 1, "Map a class to a table")
                .reallife("A student record in the university system is one row. The Java object is the same record in memory.")
                .slides("15")
                .files("student/Student.java", "db/migration/V1__init.sql", "job/JobPosting.java (enum mapping)")
                .say("The annotations are the contract between the class and the table. Flyway built the table, "
                        + "Hibernate runs in validate mode, so the two cannot drift apart silently.")
                .code("Student.java: the entity", "java", """
                        @Entity
                        @Table(name = "student")
                        public class Student {
                            @Id
                            @GeneratedValue(strategy = GenerationType.IDENTITY)
                            private Long id;

                            @Column(nullable = false)
                            private String branch;
                        }""")
                .code("V1__init.sql: the table (Flyway owns it)", "sql", """
                        create table student (
                          id     bigint generated by default as identity primary key,
                          name   varchar(120) not null,
                          email  varchar(160) not null unique,
                          branch varchar(20)  not null,
                          cgpa   numeric(3,1) not null
                        );""")
                .code("JobPosting.java: enum as text", "java", """
                        @Enumerated(EnumType.STRING)   // stores OPEN or CLOSED, not 0 or 1
                        private JobStatus status = JobStatus.OPEN;""")
                .predict("Change @Column(nullable = false) private String branch; to @Column(name = \"department\", nullable = false). Start the app. What happens?",
                        "It refuses to start. The column department does not exist in table student, and ddl-auto=validate checks the mapping at startup. Put the annotation back.")
                .breakIt("Thought experiment, do not run: with EnumType.ORDINAL the column holds 0 and 1. Insert a new value in the middle of the enum next year and every old row silently changes meaning.")
                .get("Compare the mapping with the real table", "/examples/run/h1/mapping", 200,
                        "Left side: fields read from the @Column annotations. Right side: columns read from information_schema. verdict says they agree.")
                .watch("This button uses plain JDBC, so the request log shows 0 Hibernate statements. The real check happens once, at startup.");
    }

    private static Example h2() {
        return new Example("h2", "Hibernate", 1, "CRUD without writing SQL")
                .reallife("Every admin screen in every college portal: list, add, edit, delete.")
                .slides("16")
                .files("student/StudentRepository.java", "student/StudentService.java", "page /students")
                .say("That method has no body. Spring reads the name: branch equals, cgpa at least, order by cgpa descending.")
                .code("StudentRepository.java: the method name is the query", "java", """
                        List<Student> findByBranchIgnoreCaseAndCgpaGreaterThanEqualOrderByCgpaDesc(
                                String branch, BigDecimal minCgpa);""")
                .code("The SQL Hibernate prints in the console", "sql", """
                        select ... from student
                        where upper(branch) = upper(?) and cgpa >= ?
                        order by cgpa desc""")
                .code("Test (already in the repo: ExamplesTest)", "java", """
                        var found = students.findByBranchIgnoreCaseAndCgpaGreaterThanEqualOrderByCgpaDesc("ce", new BigDecimal("8.0"));
                        assertThat(found).extracting(Student::getName)
                                .containsExactly("Meera Desai", "Asha Patel", "Nisha Parmar");""")
                .get("CE students with CGPA 8 or more, best first", "/students?branch=CE&minCgpa=8", 200,
                        "Meera 9.1, Asha 8.6, Nisha 8.0. Exactly one select in the console.")
                .get("All students (no filter)", "/students", 200, "Eight students, one select.")
                .watch("Open /students, add, edit, delete a student. After each click point at insert, update, delete in the console.");
    }

    private static Example h3() {
        return new Example("h3", "Hibernate", 2, "Relationships: companies, jobs, applications")
                .reallife("A food-delivery app. One restaurant has many dishes. Many customers order many dishes. The order is its own thing and carries a status and a time. Here the order slip is Application.")
                .slides("17, 18")
                .files("company/Company.java", "job/JobPosting.java", "application/Application.java", "application/ApplicationRepository.java")
                .say("The side that holds the foreign key owns the relationship. The other side only points back with mappedBy.")
                .code("JobPosting.java: the owning side (job_posting.company_id)", "java", """
                        @ManyToOne(fetch = FetchType.LAZY, optional = false)
                        @JoinColumn(name = "company_id")
                        private Company company;""")
                .code("Company.java: the inverse side", "java", """
                        @OneToMany(mappedBy = "company")
                        private List<JobPosting> postings = new ArrayList<>();""")
                .code("New: My applications, naive version (no fetch plan)", "java", """
                        // ApplicationRepository.java
                        List<Application> findByStudentEmailIgnoreCase(String email);

                        // ApplicationController.java
                        @GetMapping("/applications/mine")
                        public String mine(@RequestParam String email,
                                           @RequestParam(defaultValue = "false") boolean slow, Model model) {
                            model.addAttribute("rows", applications.mine(email, slow));
                            return "applications/list";   // reuse the existing template
                        }""")
                .predict("Which table holds the foreign key between company and job?",
                        "job_posting.company_id. So JobPosting is the owning side; Company.postings only says mappedBy.")
                .get("My applications, naive: count the selects", "/applications/mine?email=asha@ppsu.example&slow=true", 200,
                        "Asha has 3 applications, yet the console shows 8 statements: 1 list + 1 student + 3 jobs + 3 companies. The same bug as the 101 query page, in code written five minutes ago. Fixed in H5.")
                .watch("Count the select lines. The request log below shows the number for you.");
    }

    private static Example h4() {
        return new Example("h4", "Hibernate", 2, "Three ways to ask the database")
                .reallife("Asking a librarian: by exact title (derived), by a description you write (JPQL), or just the shelf labels (projection).")
                .slides("19")
                .files("job/JobRepository.java", "job/JobApplicantCount.java", "job/JobApiController.java")
                .say("Derived when the question fits in a method name. JPQL when you must control joins. Projection when you need two columns, not the whole entity. Native SQL exists; we do not use it today because it ties you to one database.")
                .code("Derived query", "java", "boolean existsByTitleIgnoreCase(String title);")
                .code("JPQL with @Query (join fetch)", "java", """
                        @Query("select j from JobPosting j join fetch j.company c "
                             + "where lower(c.city) = lower(:city) and j.status = ...OPEN")
                        List<JobPosting> findOpenByCity(@Param("city") String city);""")
                .code("Projection: only two columns", "java", """
                        @Query("select j.title as title, j.company.name as companyName from JobPosting j where j.status = :status")
                        List<JobSummary> summaries(@Param("status") JobStatus status);""")
                .code("New: aggregate projection, applicants per job (zero included)", "java", """
                        @Query(\"""
                                select j.title as title, count(a) as applicants
                                from JobPosting j left join Application a on a.job = j
                                group by j.title
                                order by count(a) desc, j.title
                                \""")
                        List<JobApplicantCount> applicantsPerJob();""")
                .predict("If we used 'from Application a group by a.job.title' instead, which jobs disappear?",
                        "Jobs with zero applicants: there is no application row to group. The left join keeps them with count 0.")
                .get("Applicants per job, busiest first", "/api/jobs/popular", 200,
                        "Busiest jobs first. In the seed data every job has at least one applicant, so add a new posting on /jobs/new (nobody has applied) and run it again: it appears at the bottom with 0.")
                .get("Projection: two columns only", "/api/jobs/summaries", 200,
                        "The console select lists title and company name, not every column.")
                .get("JPQL with join fetch: one select", "/jobs?city=Surat", 200, "Three Surat postings, one select with a join.")
                .watch("Live trick for the PREDICT: add a posting first, then compare with an inner join. Cross-check in SQL: select job_id, count(*) from app.application group by job_id order by 2 desc; Delete the demo posting afterwards.");
    }

    private static Example h5() {
        return new Example("h5", "Hibernate", 3, "LAZY, EAGER and the N+1 problem")
                .reallife("The page that asked the database 101 times. A waiter who carries one dish per trip, versus the tray.")
                .slides("20, 21, 22")
                .files("application/ApplicationService.java (listSlow, listFast, mine)", "application/ApplicationRepository.java", "test QueryCountTest")
                .say("The database is not slow. The code asks too often. EAGER does not fix it. Fetch what you need, on purpose.")
                .code("Three versions of the same page", "text", """
                        LAZY loop         26 statements   1 list + 8 students + 12 jobs + 5 companies
                        Batch size 20      4 statements   profile local,batch  (hibernate.default_batch_fetch_size=20)
                        JOIN FETCH         1 statement    findAllWithDetails()""")
                .code("The fix for My applications: an entity graph", "java", """
                        @EntityGraph(attributePaths = {"student", "job", "job.company"})
                        List<Application> findWithGraphByStudentEmailIgnoreCase(String email);""")
                .code("Check: exactly one statement (pattern from QueryCountTest)", "java", """
                        stats.clear();
                        assertThat(service.mine("asha@ppsu.example", false)).hasSize(3);
                        assertThat(stats.getPrepareStatementCount()).isEqualTo(1);""")
                .predict("20 applications on one page, LAZY loop: 1, 5, 26 or 100 queries?", "26.")
                .breakIt("1) Remove @Transactional from listSlow() and open /applications?slow=true: LazyInitializationException. open-in-view=false is on purpose, so students meet it here, not in production. "
                        + "2) Switch Application.student to EAGER: the page still fires extra selects, and now every page that loads an application pays for the student. EAGER does not fix N+1.")
                .get("Applications, slow: 26 statements", "/applications?slow=true", 200, "26 statements in the request log.")
                .get("Applications, fast: JOIN FETCH", "/applications", 200, "1 statement.")
                .get("My applications, naive: 8 statements", "/applications/mine?email=asha@ppsu.example&slow=true", 200, "Same three rows as below, eight statements.")
                .get("My applications, entity graph: 1 statement", "/applications/mine?email=asha@ppsu.example", 200, "Same three rows, one statement. The best three minutes of the Hibernate part.")
                .watch("Run naive, then graph, and compare the SQL column in the request log below.");
    }

    private static Example h6() {
        return new Example("h6", "Hibernate", 3, "The persistence context: lifecycle, dirty checking, one object per row")
                .reallife("The attendance register. Pencil (new), ink (being tracked), left the room (detached), struck off (removed).")
                .slides("23, 24")
                .files("application/ApplicationService.java: shortlist()", "examples/ExampleLab.java")
                .say("Only a persistent object is tracked. Hibernate keeps a snapshot when it loads, and at flush writes the difference. The first-level cache lives inside one session and you cannot turn it off.")
                .code("shortlist(): no save() anywhere", "java", """
                        @Transactional
                        public void shortlist(Long id) {
                            Application a = applications.findById(id).orElseThrow();
                            a.setStatus(ApplicationStatus.SHORTLISTED);
                        }   // commit: update application set status=?, version=? where id=? and version=?""")
                .code("The four states", "java", """
                        Student s = new Student(...);   // TRANSIENT: Hibernate does not know it
                        em.persist(s);                  // PERSISTENT: tracked, IDENTITY ran the insert
                        em.detach(s);                   // DETACHED: changes are not seen
                        em.remove(em.find(Student.class, s.getId()));   // REMOVED: delete at commit""")
                .code("First-level cache", "java", """
                        var first  = em.find(Application.class, 1L);
                        var second = em.find(Application.class, 1L);
                        // second == first, and only one select ran""")
                .predict("shortlist() has no save() call. Will the row update?",
                        "Yes. Dirty checking writes: update application set status=?, version=? where id=? and version=?")
                .get("Walk through the four states", "/examples/run/h6/lifecycle", 200, "Four steps, each with what Hibernate did. Rolled back at the end.")
                .get("Dirty checking: no save()", "/examples/run/h6/dirty-checking", 200, "Status changes, version goes up by one, one update statement.")
                .get("First-level cache", "/examples/run/h6/first-level-cache", 200, "Two finds, one statement, same object. After clear(), a second select.")
                .watch("Each button runs in a transaction that is rolled back, so you can click as often as you like.");
    }

    private static Example h7() {
        return new Example("h7", "Hibernate", 3, "Transactions and optimistic locking")
                .reallife("A bank transfer (debit and credit together or not at all), and two admins editing the same row in two browser tabs.")
                .slides("25")
                .files("application/ApplicationService.java: bulkShortlist(), changeStatus()", "test ApplicationServiceTest")
                .say("Transactions protect consistency inside one request. Versions protect it between two humans.")
                .code("All or nothing", "java", """
                        @Transactional
                        public void bulkShortlist(List<Long> ids) {
                            for (Long id : ids) {
                                Application a = applications.findById(id)
                                        .orElseThrow(() -> new NotFoundException("Application " + id));
                                a.setStatus(ApplicationStatus.SHORTLISTED);
                            }
                        }   // one bad id: everything rolls back""")
                .code("Stale form: the version decides", "java", """
                        if (!a.getVersion().equals(form.version()))
                            throw new ObjectOptimisticLockingFailureException(Application.class, form.id());
                        a.setStatus(form.status());   // update ... where id=? and version=?""")
                .predict("bulkShortlist([1, 2, 9999]): what is left in the database?", "Nothing changed. The exception rolled back the changes made earlier in the loop.")
                .post("Bulk shortlist with a bad id", "/applications/bulk-shortlist", "ids=1&ids=2&ids=9999", FORM, 404,
                        "404 page. Open /applications afterwards: rows 1 and 2 are unchanged.", false)
                .get("Open the status form (do this in two tabs)", "/applications/1/status", 200,
                        "Save in tab A (version 0 to 1). Save in tab B: 409, someone changed this before you. Zero rows matched: where id=? and version=?")
                .watch("The two-tab test is manual on purpose: it needs two humans.");
    }

    private static Example h8() {
        return new Example("h8", "Hibernate", 4, "Bulk operations: one UPDATE instead of N")
                .reallife("Result day. The placement cell shortlists 500 applications at once.")
                .slides("none yet (appendix)")
                .files("application/ApplicationRepository.java: updateStatusIn()", "application/ApplicationService.java: bulkShortlistFast()")
                .say("One statement instead of two per row. The catch is the advanced lesson: a bulk update bypasses the persistence context and does not touch the version column.")
                .code("One UPDATE for many rows", "java", """
                        @Modifying(clearAutomatically = true, flushAutomatically = true)
                        @Query("update Application a set a.status = :status where a.id in :ids")
                        int updateStatusIn(@Param("ids") Collection<Long> ids, @Param("status") ApplicationStatus status);

                        @Transactional
                        public int bulkShortlistFast(List<Long> ids) {
                            return applications.updateStatusIn(ids, ApplicationStatus.SHORTLISTED);
                        }""")
                .code("The catch", "text", """
                        - skips the persistence context: loaded entities do not see the change (hence clearAutomatically)
                        - skips @Version: optimistic locking no longer protects those rows
                        - skips entity callbacks and your business rules
                        Use it for large, simple, trusted changes only.""")
                .predict("Bulk JPQL update: does @Version change?", "No, unless you handle it yourself.")
                .get("Loop versus one UPDATE, with versions", "/examples/run/h8/compare", 200,
                        "Loop: 6 statements for 3 rows and the versions go up. Bulk: 1 statement and the versions do not move.")
                .watch("Talking point, not a demo: JDBC insert batching does not work with IDENTITY ids, because Hibernate must run each insert to learn the id. Real batch inserts use a sequence.");
    }

    // ===================================== Part B. Spring MVC =====================================

    private static Example m1() {
        return new Example("m1", "Spring MVC", 1, "Controllers and request parameters")
                .reallife("Every URL you type or tap is a method call on a server.")
                .slides("30")
                .files("job/JobController.java", "job/JobApiController.java")
                .say("Spring converted the text 6 into a BigDecimal for us. When it cannot, the user gets a 400, not a stack trace.")
                .code("JobController.java", "java", """
                        @GetMapping
                        String list(@RequestParam(required = false) String city, Model model) { ... }   // /jobs?city=Surat

                        @GetMapping("/{id}")
                        String detail(@PathVariable Long id, Model model) { ... }                      // /jobs/7""")
                .code("New: a numeric parameter with automatic conversion", "java", """
                        // JobApiController.java
                        @GetMapping("/paying")
                        List<JobView> paying(@RequestParam BigDecimal minLpa) { return jobs.paying(minLpa); }

                        // JobRepository.java
                        @EntityGraph(attributePaths = "company")
                        List<JobPosting> findByMinPackageLpaGreaterThanEqualOrderByMinPackageLpaDesc(BigDecimal minLpa);""")
                .get("minLpa=6: 200, best package first", "/api/jobs/paying?minLpa=6", 200, "JSON list, highest minimum package first.")
                .get("Parameter missing: 400", "/api/jobs/paying", 400, "The required parameter is missing.")
                .get("Not a number: 400", "/api/jobs/paying?minLpa=abc", 400, "abc cannot be converted to a number.")
                .get("Job 7 (PathVariable)", "/jobs/7", 200, "One job, one select with a join.");
    }

    private static Example m2() {
        return new Example("m2", "Spring MVC", 2, "Model, view name, and a template that stays simple")
                .reallife("The waiter reads the order; the kitchen decides what is closing soon.")
                .slides("31")
                .files("job/JobController.java: list()", "job/JobView.java", "templates/jobs/list.html")
                .say("A template should only display. The decision 'closing soon' lives in Java, where we can test it. The page receives JobView records, never entities.")
                .code("JobView.java: a rule on the record", "java", """
                        public boolean closingSoon() {
                            LocalDate today = LocalDate.now();
                            return !lastDate.isBefore(today) && !lastDate.isAfter(today.plusDays(3));
                        }""")
                .code("jobs/list.html: the template only asks", "html", """
                        <td><a th:href="@{/jobs/{id}(id=${j.id})}" th:text="${j.title}">Title</a>
                            <span class="muted" th:if="${j.closingSoon()}"> (closing soon)</span></td>""")
                .get("Open jobs", "/jobs", 200, "No badge yet: no posting ends within 3 days.")
                .watch("Edit one posting's last date to tomorrow on /jobs/{id}/edit, then reload /jobs: the badge appears.");
    }

    private static Example m3() {
        return new Example("m3", "Spring MVC", 2, "Forms and validation: never trust the browser")
                .reallife("The guard at the gate checks your ID card so bad data never reaches the store.")
                .slides("32")
                .files("application/ApplyForm.java", "application/ApplicationController.java: apply()")
                .say("Client-side checks are for convenience; server-side checks are for safety. curl has no HTML5 required attribute, yet the server still rejects the empty email.")
                .code("ApplyForm.java", "java", """
                        public record ApplyForm(
                            @NotBlank(message = "Email is required")
                            @Email(message = "Enter a valid email") String email) {}""")
                .code("The controller: errors come back to the same form, success redirects", "java", """
                        @PostMapping("/jobs/{id}/apply")
                        public String apply(@PathVariable Long id, @Valid @ModelAttribute("form") ApplyForm form,
                                            BindingResult result, Model model, RedirectAttributes redirect) {
                            if (result.hasErrors()) { ...; return "apply"; }      // 200, same form
                            applications.apply(id, form.email());
                            redirect.addFlashAttribute("message", "Application submitted");
                            return "redirect:/applications";                       // Post-Redirect-Get: 302
                        }""")
                .predict("Submit an empty email. What comes back?", "The same form with 'Email is required', status 200 (it is a page, not an API).")
                .post("POST with an empty email (like curl)", "/jobs/1/apply", "email=", FORM, 200,
                        "200 and the form again. No service call, no SQL.", false)
                .watch("Happy path by hand: apply with yash@ppsu.example on /jobs/1/apply. The request log shows POST -> 302, then GET /applications. Press F5: nothing is submitted twice. Withdraw the application afterwards on /applications.");
    }

    private static Example m4() {
        return new Example("m4", "Spring MVC", 3, "REST: the same data as JSON, and a proper 201")
                .reallife("The portal's mobile app does not want HTML. It wants the same data as JSON.")
                .slides("33")
                .files("application/ApplicationApiController.java", "job/JobApiController.java")
                .say("Same service as the HTML form. Different output. One business rule, two doors.")
                .code("ApplicationApiController.java", "java", """
                        @RestController
                        @RequestMapping("/api/applications")
                        class ApplicationApiController {
                            record ApplyRequest(@NotNull Long jobId, @NotBlank @Email String email) {}

                            @PostMapping
                            ResponseEntity<ApplicationRow> apply(@Valid @RequestBody ApplyRequest request) {
                                Application saved = applications.apply(request.jobId(), request.email());
                                return ResponseEntity.created(URI.create("/api/applications/" + saved.getId()))
                                        .body(applications.get(saved.getId()));
                            }
                        }""")
                .code("curl", "text", """
                        curl -i -X POST localhost:8080/api/applications \\
                             -H "Content-Type: application/json" \\
                             -d '{"jobId":1,"email":"isha@ppsu.example"}'""")
                .post("New application: 201 + Location (run first)", "/api/applications", "{\"jobId\":1,\"email\":\"isha@ppsu.example\"}", JSON, 201,
                        "201 with a Location header. After it runs, an Undo button deletes what it created.", true)
                .post("Same request again: 409 already applied", "/api/applications", "{\"jobId\":1,\"email\":\"isha@ppsu.example\"}", JSON, 409,
                        "409 Conflict as JSON.", true)
                .post("Unknown email: 404", "/api/applications", "{\"jobId\":1,\"email\":\"nobody@ppsu.example\"}", JSON, 404, "404 Not Found.", false)
                .post("Closed job: 409", "/api/applications", "{\"jobId\":2,\"email\":\"isha@ppsu.example\"}", JSON, 409, "The QA Automation Trainee posting is closed.", false)
                .post("Missing fields: 400", "/api/applications", "{}", JSON, 400, "400 with an errors object (see M5).", false)
                .watch("The first run changes data. Press Undo, or restart with the local profile, before the next audience.");
    }

    private static Example m5() {
        return new Example("m5", "Spring MVC", 3, "Errors: one handler for every failure")
                .reallife("The kitchen fire is kept out of the dining room.")
                .slides("34")
                .files("common/GlobalExceptionHandler.java", "common/ApiExceptionHandler.java")
                .say("Same exception, two renderings: a friendly page for a person, JSON for a program. The user never sees a stack trace.")
                .code("ApiExceptionHandler.java: field-level errors for @Valid @RequestBody", "java", """
                        @ExceptionHandler(MethodArgumentNotValidException.class)
                        ProblemDetail invalid(MethodArgumentNotValidException e) {
                            ProblemDetail problem = ProblemDetail.forStatusAndDetail(HttpStatus.BAD_REQUEST, "Validation failed");
                            Map<String, String> errors = new LinkedHashMap<>();
                            e.getBindingResult().getFieldErrors().forEach(fe -> errors.put(fe.getField(), fe.getDefaultMessage()));
                            problem.setProperty("errors", errors);
                            return problem;
                        }""")
                .code("Checklist", "text", """
                        /jobs/9999                     404 page   GlobalExceptionHandler.notFound
                        /api/jobs/9999                 404 JSON   ApiExceptionHandler.notFound
                        apply twice, same email        409        DuplicateApplicationException (a ConflictException)
                        delete a job with applications 409        JobService.delete
                        stale status form, two tabs    409        ObjectOptimisticLockingFailureException
                        empty email in the form        200        BindingResult in the controller""")
                .get("Missing job as a page", "/jobs/9999", 404, "A friendly HTML page.")
                .get("Missing job as JSON", "/api/jobs/9999", 404, "A JSON problem document.")
                .post("Empty JSON body: 400 with an errors object", "/api/applications", "{}", JSON, 400,
                        "errors lists jobId and email.", false);
    }

    private static Example m6() {
        return new Example("m6", "Spring MVC", 3, "A HandlerInterceptor that prints the SQL count of every request")
                .reallife("A taxi meter: every ride shows what it cost. Here, every request shows how many SQL statements it caused.")
                .slides("none yet (appendix)")
                .files("common/QueryCountInterceptor.java", "common/WebConfig.java", "common/RequestLog.java")
                .say("Hibernate decides how often we ask the database. Spring MVC decides what the user sees. This interceptor joins both halves of the day. "
                        + "A filter sits at the servlet level and knows nothing about Spring. An interceptor sits around the controller call. @ControllerAdvice handles exceptions. Three tools, three jobs.")
                .code("QueryCountInterceptor.java", "java", """
                        @Override
                        public boolean preHandle(HttpServletRequest req, HttpServletResponse res, Object handler) {
                            req.setAttribute("qc.sql", stats.getPrepareStatementCount());
                            req.setAttribute("qc.start", System.nanoTime());
                            return true;
                        }

                        @Override
                        public void afterCompletion(HttpServletRequest req, HttpServletResponse res, Object h, Exception ex) {
                            long sql = stats.getPrepareStatementCount() - (Long) req.getAttribute("qc.sql");
                            log.info("{} {} -> {} | {} SQL | {} ms", req.getMethod(), req.getRequestURI(), res.getStatus(), sql, ms);
                        }""")
                .code("WebConfig.java: register it", "java", """
                        @Override
                        public void addInterceptors(InterceptorRegistry registry) {
                            registry.addInterceptor(queryCount).excludePathPatterns("/css/**", "/actuator/**");
                        }""")
                .code("Console", "text", """
                        GET /applications?slow=true -> 200 | 26 SQL | 48 ms
                        GET /applications           -> 200 | 1 SQL  | 9 ms""")
                .get("Slow page: 26 SQL", "/applications?slow=true", 200, "26 in the request log.")
                .get("Fast page: 1 SQL", "/applications", 200, "1 in the request log.")
                .get("Student filter: 1 SQL", "/students?branch=CE&minCgpa=8", 200, "1 in the request log.")
                .watch("Honest limit: the counter is global to the application, so with several users at once the numbers mix. A teaching tool, not production monitoring.");
    }

    private static Example m7() {
        return new Example("m7", "Spring MVC", 4, "Layers and the DTO boundary")
                .reallife("The DTO is the plated dish; the entity is the kitchen container.")
                .slides("35")
                .files("job/JobView.java", "application/ApplicationRow.java", "examples/ExamplesController.java: rawEntity()")
                .say("Returning entities leaks your table design, fails on lazy proxies, and can recurse forever.")
                .code("Wrong on purpose (this endpoint exists only for the demo)", "java", """
                        @GetMapping("/examples/run/m7/raw-entity")
                        @ResponseBody
                        List<JobPosting> rawEntity() { return jobRepository.findAll(); }   // no DTO""")
                .breakIt("Run it, read the 500, then compare with /api/jobs, which returns JobView records.")
                .get("Return entities directly: expect a 500", "/examples/run/m7/raw-entity", 500,
                        "JSON serialization fails on the lazy company proxy (and Company.postings points back at jobs).")
                .get("The same data through the DTO", "/api/jobs", 200, "Flat JobView records. Works.");
    }

    private static Example m8() {
        return new Example("m8", "Spring MVC", 4, "Where to go next")
                .reallife("Today is the skeleton. A real project adds these.")
                .slides("36")
                .say("None of these are in the repo yet, so say 'next step', not 'we did it'.")
                .code("What real projects add", "text", """
                        Spring Security   login page and roles (student, placement officer); spring-boot-starter-security
                        Async requests    return Callable or DeferredResult from a controller for slow work
                        Tests             already in repo: MockMvc, DataJpaTest, query-count tests; add one per endpoint
                        Monitoring        Actuator health is on; add metrics later
                        Deployment        Docker image, then CI (.github/workflows/build.yml exists)""")
                .get("Actuator health (already on)", "/actuator/health", 200, "Status UP with the database details.");
    }
}
