-- ============================================================================
-- OPTIONAL: the complete database by hand (V1 schema + V2 seed + V3 index in one script)
-- ============================================================================
-- You normally DO NOT need this: start the app and Flyway applies the same SQL for you.
-- Use it only if you want to build the database yourself in the SQL Editor, for example to
-- show the tables before the app runs.
--
-- After running this script just start the application normally (start.cmd / start.sh).
-- application.properties has flyway.baseline-on-migrate=true with baseline-version=3, so Flyway adopts
-- the existing tables as "already at version 3" and creates its history table, without re-running V1..V3.
-- To start completely clean again, run 03_reset.sql (then Flyway builds everything itself).
-- Future migrations (V4 and up) will still be applied normally.
-- Keep this file identical to src/main/resources/db/migration/V1..V3.

create schema if not exists app;
set search_path to app;

-- ---------------------------------------------------------------- V1: tables
create table company (
  id bigint generated by default as identity primary key,
  name varchar(120) not null unique,
  city varchar(80) not null,
  website varchar(200)
);

create table job_posting (
  id bigint generated by default as identity primary key,
  company_id bigint not null references company(id),
  title varchar(150) not null unique,
  min_package_lpa numeric(5,2) not null,
  max_package_lpa numeric(5,2) not null,
  last_date date not null,
  status varchar(20) not null default 'OPEN',
  constraint ck_job_status check (status in ('OPEN','CLOSED')),
  constraint ck_job_package check (max_package_lpa >= min_package_lpa)
);
create index idx_job_company on job_posting(company_id);

create table student (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  email varchar(150) not null unique,
  branch varchar(30) not null,
  cgpa numeric(3,2) not null,
  constraint ck_student_cgpa check (cgpa between 0 and 10)
);

create table application (
  id bigint generated by default as identity primary key,
  student_id bigint not null references student(id),
  job_id bigint not null references job_posting(id),
  status varchar(20) not null default 'APPLIED',
  applied_at timestamp not null default current_timestamp,
  version bigint not null default 0,
  constraint uq_application unique (student_id, job_id),
  constraint ck_app_status check (status in ('APPLIED','SHORTLISTED','REJECTED','SELECTED'))
);
create index idx_app_student on application(student_id);
create index idx_app_job on application(job_id);

-- ---------------------------------------------------------------- V2: seed data
insert into company (name, city, website) values
 ('Nimbus Tech', 'Ahmedabad', 'https://nimbus.example'),
 ('Kesar Systems', 'Gandhinagar', 'https://kesar.example'),
 ('Gujarat Cloudworks', 'Surat', 'https://gcw.example'),
 ('Saptarishi Analytics', 'Vadodara', 'https://saptarishi.example'),
 ('BlueLotus Software', 'Rajkot', 'https://bluelotus.example');

insert into job_posting (company_id, title, min_package_lpa, max_package_lpa, last_date, status)
select c.id, v.title, v.minp, v.maxp, cast(v.ld as date), v.st
from (values
 ('Nimbus Tech','Java Backend Intern',3.0,4.5,'2026-11-30','OPEN'),
 ('Nimbus Tech','QA Automation Trainee',2.8,3.6,'2026-09-15','CLOSED'),
 ('Kesar Systems','Spring Boot Developer Trainee',3.5,5.0,'2026-12-10','OPEN'),
 ('Kesar Systems','Data Analyst Intern',3.0,4.0,'2026-11-20','OPEN'),
 ('Gujarat Cloudworks','Cloud Support Engineer',3.2,4.8,'2026-12-05','OPEN'),
 ('Gujarat Cloudworks','DevOps Trainee',3.6,5.2,'2026-12-15','OPEN'),
 ('Gujarat Cloudworks','Java Full Stack Trainee',3.4,5.0,'2026-11-28','OPEN'),
 ('Saptarishi Analytics','Python Data Engineer Trainee',3.8,5.5,'2026-12-01','OPEN'),
 ('Saptarishi Analytics','BI Developer Intern',3.0,4.2,'2026-11-25','OPEN'),
 ('BlueLotus Software','Mobile App Trainee',3.0,4.4,'2026-12-12','OPEN'),
 ('BlueLotus Software','UI Engineer Intern',2.8,4.0,'2026-11-18','OPEN'),
 ('BlueLotus Software','Technical Support Associate',2.5,3.4,'2026-12-20','OPEN')
) as v(cname, title, minp, maxp, ld, st)
join company c on c.name = v.cname;

insert into student (name, email, branch, cgpa) values
 ('Asha Patel','asha@ppsu.example','CE',8.6), ('Rohan Shah','rohan@ppsu.example','IT',7.9),
 ('Meera Desai','meera@ppsu.example','CE',9.1), ('Kabir Mehta','kabir@ppsu.example','CS',8.2),
 ('Isha Joshi','isha@ppsu.example','IT',8.8), ('Dev Trivedi','dev@ppsu.example','ITE',7.4),
 ('Nisha Parmar','nisha@ppsu.example','CE',8.0), ('Yash Gandhi','yash@ppsu.example','CS',7.7);

insert into application (student_id, job_id, status)
select s.id, j.id, v.st
from (values
 ('asha@ppsu.example','Java Backend Intern','SHORTLISTED'), ('asha@ppsu.example','Spring Boot Developer Trainee','APPLIED'),
 ('asha@ppsu.example','Java Full Stack Trainee','APPLIED'), ('rohan@ppsu.example','Java Backend Intern','APPLIED'),
 ('rohan@ppsu.example','Cloud Support Engineer','APPLIED'), ('rohan@ppsu.example','DevOps Trainee','REJECTED'),
 ('meera@ppsu.example','Spring Boot Developer Trainee','SELECTED'), ('meera@ppsu.example','Data Analyst Intern','APPLIED'),
 ('meera@ppsu.example','BI Developer Intern','SHORTLISTED'), ('kabir@ppsu.example','QA Automation Trainee','REJECTED'),
 ('kabir@ppsu.example','Python Data Engineer Trainee','APPLIED'), ('kabir@ppsu.example','Mobile App Trainee','APPLIED'),
 ('isha@ppsu.example','UI Engineer Intern','APPLIED'), ('isha@ppsu.example','Technical Support Associate','APPLIED'),
 ('isha@ppsu.example','Java Full Stack Trainee','SHORTLISTED'), ('dev@ppsu.example','Mobile App Trainee','APPLIED'),
 ('dev@ppsu.example','Cloud Support Engineer','APPLIED'), ('nisha@ppsu.example','Data Analyst Intern','APPLIED'),
 ('nisha@ppsu.example','Python Data Engineer Trainee','SHORTLISTED'), ('yash@ppsu.example','Technical Support Associate','APPLIED')
) as v(email, title, st)
join student s on s.email = v.email
join job_posting j on j.title = v.title;

-- ---------------------------------------------------------------- V3: performance index
create index idx_job_status_last_date on job_posting(status, last_date);

-- ---------------------------------------------------------------- check
select (select count(*) from company)     as companies,      -- 5
       (select count(*) from job_posting) as job_postings,   -- 12
       (select count(*) from student)     as students,       -- 8
       (select count(*) from application) as applications;   -- 20
