create table company (
  id bigint generated by default as identity primary key,
  name varchar(120) not null unique,
  city varchar(80) not null,
  website varchar(200)
);

create table job_posting (
  id bigint generated by default as identity primary key,
  company_id bigint not null references company(id),
  title varchar(150) not null unique,
  min_package_lpa numeric(5,2) not null,
  max_package_lpa numeric(5,2) not null,
  last_date date not null,
  status varchar(20) not null default 'OPEN',
  constraint ck_job_status check (status in ('OPEN','CLOSED')),
  constraint ck_job_package check (max_package_lpa >= min_package_lpa)
);
create index idx_job_company on job_posting(company_id);

create table student (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  email varchar(150) not null unique,
  branch varchar(30) not null,
  cgpa numeric(3,2) not null,
  constraint ck_student_cgpa check (cgpa between 0 and 10)
);

create table application (
  id bigint generated by default as identity primary key,
  student_id bigint not null references student(id),
  job_id bigint not null references job_posting(id),
  status varchar(20) not null default 'APPLIED',
  applied_at timestamp not null default current_timestamp,
  version bigint not null default 0,
  constraint uq_application unique (student_id, job_id),
  constraint ck_app_status check (status in ('APPLIED','SHORTLISTED','REJECTED','SELECTED'))
);
create index idx_app_student on application(student_id);
create index idx_app_job on application(job_id);
